### ISSUE TITLE
No CVE information on CentOS 8

### ISSUE THREAD

**Issue by liberodark** [liberodark/nrpe-installer#10]
Now centos 8 is out but my first test is not good news is now not possible to see cve informations.
Have ask about that :
https://www.centos.org/forums/viewtopic.php?f=57&t=71927&p=302388#p302388

Wait for more informations

**Comment by liberodark** [comment]
Test on Redhat 8 is OK work

**Comment by liberodark** [comment]
Issue open on : https://bugzilla.redhat.com/show_bug.cgi?id=1759565

**Comment by liberodark** [comment]
Issue open on : https://bugs.centos.org/view.php?id=16560

**Comment by liberodark** [comment]
Test on Fedora 31 is OK work

**Comment by liberodark** [comment]
Test on AlmaLinux 8 is KO don't work
Issue open on : https://bugs.almalinux.org/view.php?id=31

**Comment by liberodark** [comment]
RockyLinux > https://updateinfo.cefs.steve-meier.de/
Need to wait image for more tests

**Comment by andrewlukoshko** [comment]
@liberodark errata is now available for AlmaLinux
https://www.reddit.com/r/AlmaLinux/comments/m8nb60/let_there_be_errata

**Comment by liberodark** [comment]
@andrewlukoshko Thank you have test errata work.
there is still some (???) that this occurs when there is no information about the software in question. But it is possible this was not yet implemented in your errata.
I would do some further testing to confirm this. 
![image](https://user-images.githubusercontent.com/4238928/112113347-fd01e280-8bb6-11eb-8574-4e1757336598.png)

**Comment by liberodark** [comment]
Fixed by AlmaLinux
